package br.com.fiap.farmasusdigital.domain.model;

public enum EstadoConversa {
    AGUARDANDO_CPF,
    AGUARDANDO_NOME_PACIENTE,
    AGUARDANDO_NOME_MEDICAMENTO,
    AGUARDANDO_ESCOLHA_MEDICAMENTO,
    AGUARDANDO_MAIS_ITENS_OU_FINALIZAR,
    AGUARDANDO_CONFIRMACAO_CANCELAMENTO
}
